In [1]:
    %matplotlib inline
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import seaborn as sns
    sns.set()
    from scipy import optimize
    from ipywidgets import *
    from IPython.display import SVG
    from sklearn import datasets
    

In [2]:
AND = pd.DataFrame({'x1':(0,0,1,1), 'x2':(0,1,0,1), 'y':(0,0,0,1)})
AND  ##  X1 & X2 are features columns and Y is label (AND relation)

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [3]:
w=np.random.randn(3)*1e-4

In [4]:
w

array([-1.54433914e-05, -2.45193863e-05,  5.86900166e-05])

In [5]:
inputs = AND[['x1','x2']]
target = AND['y']

In [6]:
g=lambda inputs,weights: np.where(np.dot(inputs, weights)>0,1,0)

In [7]:
np.c_[np.array([1,2,3]), np.array([4,5,6])] ##example how np.c works

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
inputs=AND[['x1','x2']]
inputs

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [9]:
-np.ones((len(inputs), 1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [10]:
a=np.c_[inputs, -np.ones((len(inputs), 1))]

In [11]:
w

array([-1.54433914e-05, -2.45193863e-05,  5.86900166e-05])

In [12]:
np.dot(a,w)

array([-5.86900166e-05, -8.32094029e-05, -7.41334080e-05, -9.86527944e-05])

In [13]:
def train(inputs, targets, weights, eta, n_iterations):
    # Add the inputs that match the bias node
    inputs = np.c_[inputs, -np.ones((len(inputs),1))]

    for n in range(n_iterations):
        
        activations = g(inputs, weights);
        print(n, activations)
        weights -= eta*np.dot(np.transpose(inputs), activations - targets)
        print(n, weights)
    return(weights)

In [14]:
inputs = AND[['x1','x2']]
target = AND['y']

w= train(inputs, target, w, 0.001,20)
target

0 [0 0 0 0]
0 [ 0.00098456  0.00097548 -0.00094131]
1 [1 1 1 1]
1 [-1.54433914e-05 -2.45193863e-05  2.05869002e-03]
2 [0 0 0 0]
2 [0.00098456 0.00097548 0.00105869]
3 [0 0 0 1]
3 [0.00098456 0.00097548 0.00105869]
4 [0 0 0 1]
4 [0.00098456 0.00097548 0.00105869]
5 [0 0 0 1]
5 [0.00098456 0.00097548 0.00105869]
6 [0 0 0 1]
6 [0.00098456 0.00097548 0.00105869]
7 [0 0 0 1]
7 [0.00098456 0.00097548 0.00105869]
8 [0 0 0 1]
8 [0.00098456 0.00097548 0.00105869]
9 [0 0 0 1]
9 [0.00098456 0.00097548 0.00105869]
10 [0 0 0 1]
10 [0.00098456 0.00097548 0.00105869]
11 [0 0 0 1]
11 [0.00098456 0.00097548 0.00105869]
12 [0 0 0 1]
12 [0.00098456 0.00097548 0.00105869]
13 [0 0 0 1]
13 [0.00098456 0.00097548 0.00105869]
14 [0 0 0 1]
14 [0.00098456 0.00097548 0.00105869]
15 [0 0 0 1]
15 [0.00098456 0.00097548 0.00105869]
16 [0 0 0 1]
16 [0.00098456 0.00097548 0.00105869]
17 [0 0 0 1]
17 [0.00098456 0.00097548 0.00105869]
18 [0 0 0 1]
18 [0.00098456 0.00097548 0.00105869]
19 [0 0 0 1]
19 [0.00098456 0.000

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [15]:
g(np.c_[inputs, -np.ones((len(inputs), 1))], w)

array([0, 0, 0, 1])

In [16]:
OR = pd.DataFrame({'x1':(0,0,1,1), 'x2':(0,1,0,1), 'y':(0,1,1,1)})
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [18]:
w=np.random.randn(3)*1e-4

In [22]:
inputs=OR[['x1','x2']]
target=OR['y']

w=train(inputs, target, w, 0.25,20)

0 [0 1 1 1]
0 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
1 [0 1 1 1]
1 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
2 [0 1 1 1]
2 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
3 [0 1 1 1]
3 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
4 [0 1 1 1]
4 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
5 [0 1 1 1]
5 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
6 [0 1 1 1]
6 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
7 [0 1 1 1]
7 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
8 [0 1 1 1]
8 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
9 [0 1 1 1]
9 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
10 [0 1 1 1]
10 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
11 [0 1 1 1]
11 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
12 [0 1 1 1]
12 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
13 [0 1 1 1]
13 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
14 [0 1 1 1]
14 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
15 [0 1 1 1]
15 [4.99947286e-01 5.00029535e-01 7.80134244e-05]
16 [0 1 1 1]

In [23]:
g(np.c_[inputs, -np.ones((len(inputs), 1))], w)

array([0, 1, 1, 1])